HW 1. CLI
dedok1997/software-design pull request #1
Opened 2020-03-04 05:06 UTC by dedok1997

2020-03-14 09:41 UTC, dedok1997 commented
Не понял куда там можно библиотеку для разбора аргументов пределать. Роль этой библиотеки у меня выполняет функция matchOptions

2020-03-17 18:07 UTC, dedok1997 commented
По ходу выполнения задания с grep возникали идеи как можно улучшить текущую архитектуру или просто исправить ошибка в реализации, которые не были замечены изначально.
Чтобы не вынуждать преподавателя оставлять комментарии под устаревшим кодом, было принято решение вести разработку в той же ветке.

2020-03-23 17:46 UTC, ottergottaott requested changes
Хорошая работа, но по функциональности есть некоторые замечания
- При попытке присваивание сделать почему-то завершает работу, при присваивании без пробелов ошибка
```
[info] Running ru.jenya.cli.Appl
echo 10
10
x=10
Cannot run program "x=10" (in directory "/"): error=2, No such file or directory
```
из-за этого, в частности, не могу протестировать квотирование и какие-либо  подстановки. 
- не совсем корректная работа:
```java
echo asdfasdf | cat
 (No such file or directory)
```
asdfasdf --  не аргумент для cat, это данные, которые нужно считывать из потока, как из stdin, например
- pwd почему-то выводит относительный путь. Зачем?
- при попытке позвать `git status` все подвесилось


С точки зрения архитектуры выглядит более, чем адекватно, но все-таки не хватает более подробного текстового описания.

2020-03-23 17:46 UTC, aleksZubakov commented on src/main/scala/ru/jenya/cli/Appl.scala
> +object Appl extends App {
Не хватает комментариев, они должны быть примерно к каждой сущности и минимум к каждому публичному методу

2020-03-23 17:46 UTC, aleksZubakov commented on src/test/scala/ru/jenya/cli/ApplcicationTest.scala
> +object ApplcicationTest extends TestSuite {
Аналогично и с тестами: они должны покрывать как можно большее количество кода, а не выборочное

2020-03-23 17:46 UTC, aleksZubakov commented on src/main/scala/ru/jenya/cli/interpret/command/PWDCMD.scala
> +    val current = ctx.getOrElse(currentDir, "./")
А зачем тогда метод в `EnvUtils`?

2020-03-23 17:46 UTC, aleksZubakov commented on src/main/scala/ru/jenya/cli/interpret/envirnoment/EnvUtils.scala
> +  def currentDir(m: collection.Map[String, String]) = m.getOrElse("cur_dir", "/")
Кажется, что лучше тогда сделать вместо `ctx: collection.Map[String, String]` объект  полноценного класса, который внутри будет таскать эту мапу, а снаружи у него будет какой-то более высокоуровневый интерфейс

2020-03-23 17:47 UTC, aleksZubakov commented
По grep прокомментирую позже

2020-03-30 18:42 UTC, ottergottaott requested changes
На ошибки ввода вроде той, что ниже
```
grep -A -1 plugin build.gradle
```
пишет
```
(No such file or directory)
```
лучше, чтобы пользователю сообщалось, что проблема в аргументах, а не с тем, что файл  не найден.

Также в задании явно требовалось 
> реализовать команду grep, использующую одну из библиотек для разбора аргументов командной строки.

и 
> Ожидается обоснование выбора библиотеки для работы с аргументами --- какие были рассмотрены, почему выбрана именно эта


Также не нашел тесты для `grep`

2020-03-30 18:42 UTC, aleksZubakov commented on src/main/scala/ru/jenya/cli/interpret/command/grep/GrepCMD.scala
> +object GrepCMD extends CMD {
И здесь должны быть комментарии.

2020-03-30 18:42 UTC, aleksZubakov commented on src/main/scala/ru/jenya/cli/interpret/command/grep/GrepCMD.scala
> +      val writer = new OutputStreamWriter(out)
А закрыть `writer`?

2020-03-31 13:38 UTC, dedok1997 commented on src/main/scala/ru/jenya/cli/interpret/command/grep/GrepCMD.scala
> +      val writer = new OutputStreamWriter(out)
Он [вроде бы](https://stackoverflow.com/questions/28276423/is-it-necessary-to-close-each-nested-outputstream-and-writer-separately) закрывает базовый стрим

2020-05-13 08:56 UTC, dedok1997 commented on src/main/scala/ru/jenya/cli/interpret/command/grep/GrepCMD.scala
> +      val writer = new OutputStreamWriter(out)
А нет. Поправил

2020-05-13 08:59 UTC, dedok1997 commented on src/main/scala/ru/jenya/cli/interpret/envirnoment/EnvUtils.scala
> +  def currentDir(m: collection.Map[String, String]) = m.getOrElse("cur_dir", "/")
Ага, действительно удобнее. Заменил и теперь можно легко подменить в случае необходимости

2020-05-13 09:03 UTC, dedok1997 commented on src/main/scala/ru/jenya/cli/interpret/command/PWDCMD.scala
> +    val current = ctx.getOrElse(currentDir, "./")
Забыл заменить, когда его добавлял. Пофиксил

2020-05-18 21:19 UTC, aleksZubakov commented
Тестов, конечно, стоит больше писать.

В остальном ок, засчитываю

2020-05-19 12:05 UTC, merged